# Generated by Django 4.2 on 2026-03-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_reviewmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
