# Generated by Django 4.2 on 2026-03-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_reviewmodel_rating_alter_reviewmodel_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
